theme: jekyll-theme-cayman
title: Bomber's Experiments
description: A collection of my personal and open projects.
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
